version: "3"

services:
  postgres:
    image: postgres:9.5-alpine
    volumes:
      - ./db-setup:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - "ADVERTISED_HOST=localhost"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"

  ultraboost:
    build:
      ./ultraboost
    ports:
      - "9000:9000"
    depends_on:
      - kafka
      - postgres

  powerboost:
    build:
      ./powerboost
    ports:
      - 9010:9010
    depends_on:
      - kafka
      - postgres
      - ultraboost

volumes:
  db-data:
